### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by KizzyCode** [jedisct1/spake2-ee#5]
Hi, I'm wondering if this project is still alive…?
And I know that you want to make a version using libhydrogen, but it'd be cool if you could exchange the providers. Since libsodium is gold-standard, nobody objects anymore – this wouldn't be the case with libhydrogen (which is stupid, but… 😕)

**Comment by jedisct1** [comment]
PAKEs are being heavily discussed, analyzed and compared right now.

SPAKE2+EE remains a solid choice, and you are in a better state than 99.999% of the companies having ended up on haveibeenpwned if you use it. But something else may eventually get more traction, depending on the outcome of these discussions.

I don't use libsodium any more. So, if I ever need a PAKE, I probably wouldn't use it to write a new implementation. wasm-crypto seems like a better fit.
